# Generated by Django 3.0.7 on 2021-01-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210102_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.FileField(null=True, upload_to='article_img/'),
        ),
    ]
